apiVersion: apps/v1
kind: Deployment
metadata:
  name: disable-or-enable-account
  labels:
    app: disable-or-enable-account-app
  namespace: account-update
spec:
  selector:
    matchLabels:
      app: disable-or-enable-account-app
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: disable-or-enable-account-app
    spec:
      containers:
      - name: disable-or-enable-account-app
        image: conano/disable-or-enable-account-handler:0.0.1-4
        envFrom:
        - secretRef:
            name: disable-or-enable-account-secret
        imagePullPolicy: IfNotPresent        
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        